### PR TITLE
Simple idea for cancel take

### PR DESCRIPTION
**Pull request by arkanoider**
Hi @grunch,

a simple idea for #314.

Just adding some checks inside cancel.rs could lead to rewind to pending state the taken order imo.

Let me know your thoughts.

In this way cancel command would cancel a take too.

### CODE REVIEW

**Review by Catrya — COMMENTED** [review]
It only allows to cancel a take of buy order, but not a take of a sell order.
Even though it cancels the take of buy order, it sends the message Not Allowed to the taker when cancell it.

**Comment by arkanoider** [comment]
> It only allows to cancel a take of buy order, but not a take of a sell order.
> Even though it cancels the take of buy order, it sends the message Not Allowed to the taker when cancell it.

Thanks for the tests @Catrya !
Probably i did some typo logic should in the same way, will check. Message can be changed, no issue.

**Comment by arkanoider** [comment]
> It only allows to cancel a take of buy order, but not a take of a sell order. Even though it cancels the take of buy order, it sends the message Not Allowed to the taker when cancell it.

You use the invoice in the take sell command @Catrya ?

**Comment by arkanoider** [comment]
Closing this. Not the right way to do cancel take.

**Comment by arkanoider** [comment]
Reopened PR - fixed.

**Review by Catrya — COMMENTED** [review]
It allows users to cancel any take: buy or sell

But now this also happens:
1. taker takes the order and does his part
2. order goes to status `waiting-buyer-invoice` or `waiting-payment`
3. Maker sends `cancel` before doing his part
4. The order goes back to status `Pending` (and of course appears in listorders), but it should be cancelled

in the current version if the maker tries to cancel the order before doing his part Mostro doesn't allow it (it doesn't send a cantDo message but it just stays in the status waiting-buyer-invoice or waiting-payment)

**Review by Catrya — APPROVED** [review]
ACK
It works well!

**Review by grunch — APPROVED** [review]
LGTM

**Pull request merged**
