### PR TITLE
Fix for vote user

### PR DESCRIPTION
**Pull request by arkanoider**
Hi @grunch ,

set content of dm from mostro to signal user to vote to `None`

### CODE REVIEW

**Comment by grunch** [comment]
this PR is still in progress?

**Comment by arkanoider** [comment]
I wanted to fix at least the other point, but i think that for tonite i am finished....:)

**Comment by grunch** [comment]
great, after you finish make sure you marked it as `ready for review` that way contributors know that we can review it, get rest 😃

**Comment by grunch** [comment]
is this ready for review?

**Review by grunch — APPROVED** [review]
LGTM

**Pull request merged**
