### PR TITLE
Fix panic ln node

### PR DESCRIPTION
**Pull request by arkanoider**
Hi @grunch ,

this should fix the possible ln node without blocking Mostrod.
To be tested.

### CODE REVIEW

**Review by Catrya — COMMENTED** [review]
I tested it and it works fine

**Comment by arkanoider** [comment]
great, mostrod does not panic when ln is down and keeps running printing a log?

**Comment by Catrya** [comment]
> great, mostrod does not panic when ln is down and keeps running printing a log?

Yes, this is the log:
```
2024-09-11T15:46:14.421235Z  WARN mostrod::app: Error in AddInvoice with context status: Cancelled, message: "status: Unavailable, message: \"error trying to connect: tcp connect error: Connection refused (os error 111)\", details: [], metadata: MetadataMap { headers: {} }", details: [], metadata: MetadataMap { headers: {} }
```

**Review by grunch — APPROVED** [review]
LGTM

**Pull request merged**
