### PR TITLE
Added a check in dispute.rs

### PR DESCRIPTION
**Pull request by arkanoider**
Hi @grunch ,

this is for #220 from @Catrya .

Added a check like this in `dispute.rs`
```Rust
fn check_order_status_for_dispute(status: &str) -> bool {
    match Status::from_str(status).unwrap() {
        Status::Success => true,
        _ => false,
    }
}

```

I just check that order is in success state to block dispute creation for now, feel free to add other states.

### CODE REVIEW

**Comment by Catrya** [comment]
Hi @arkanoider, if users canceled the order they can also open a dispute, so I thought that mostro could also verify that the order was not cancelled.

but speaking with @grunch he says that to open a dispute what we must do is check if the status of the order is active or fiat-sent, which is a much better idea than mine

**Comment by arkanoider** [comment]
Sounds good! Wiill fix.

**Comment by arkanoider** [comment]
@Catrya @grunch 

Dispute should be available only for `Active` and `FiatSent` orders now.

**Review by grunch — APPROVED** [review]
LGTM

**Pull request merged**
