### PR TITLE
Add Docker setup and guide for building and running MostroP2P

### PR DESCRIPTION
**Pull request by tincho70**
### Summary
This PR adds Docker support to the MostroP2P repository, including a new Docker guide (DOCKER.md) and all necessary files to build and run the application using Docker and Docker Compose.

### Changes
- Added `DOCKER.md` file with detailed instructions for:
  - Prerequisites for Docker and Docker Compose
  - Building and running the Docker container
  - Docker Compose configuration
- Added `Dockerfile` to define the Docker image build process.
- Added `compose.yml` for Docker Compose configuration.
- Added `empty.mostro.db`, an empty SQLite database required by the application.
- Added `settings.docker.toml`, a configuration file (template) for the application.
- Added `start.sh`, a script to start the application inside the Docker container.

### Why
These additions will help users and developers set up and run the MostroP2P application using Docker and Docker Compose, ensuring a consistent and simplified setup process. This will also make it easier to manage dependencies and environment configuration.

@grunch @arkanoider Please review the changes and provide feedback.

### CODE REVIEW

**Comment by arkanoider** [comment]
If it works @grunch i think it's a super cool add, ease the process to play with mostrod.
For me it's a merge!

**Review by grunch — APPROVED** [review]
Great add @tincho70 LGTM!

**Review by arkanoider — COMMENTED** [review]
Merge it!

**Comment by grunch** [comment]
> Merge it!

approve it

**Pull request merged**
