### PR TITLE
Issue invoice values

### PR DESCRIPTION
**Pull request by arkanoider**
Hi @grunch ,

this could a quick trick to solve all the points in #199 , but please check. Just compiled.

### CODE REVIEW

**Review by grunch — CHANGES_REQUESTED** [review]
This is the second case in #199 

I did this:
```bash
mcli neworder -k buy -c ars -f 1000 -m "MP lemon belo brubank uala" -i lnbcrt500u1pjlx8h2pp59j3gqf4t557y7crssk4vf4s5n8emqh3pa82g4vx4n8ujyfdp03nsdqqcqzzsxqyz5vqsp5jzc9aww26844a6c2sp5nyyv9hvzy9zhapwa78vx5lynx7ylt70gs9qyyssqcvwfpf99ttf7y02tzqj2e7nfzn2tptn0s269pjrd9xw7fspchl35nkfzedlyf65jh8ylq8u433puux8846j6cr4qzzckdhfvg0n0tkqpjxjt8m -a 100000
┌──────────┬─────────────┬───────────┬─────────────┬────────────────────────────┬───────────┐
│ Buy/Sell ┆ Sats Amount ┆ Fiat Code ┆ Fiat Amount ┆       Payment method       ┆ Premium % │
╞══════════╪═════════════╪═══════════╪═════════════╪════════════════════════════╪═══════════╡
│    buy   ┆    100000   ┆    ARS    ┆     1000    ┆ MP lemon belo brubank uala ┆     0     │
└──────────┴─────────────┴───────────┴─────────────┴────────────────────────────┴───────────┘
Check your order! Is it correct? (Y/n) > 
Message correctly sent to Mostro! Check messages with getdm or listorders command
```
and Mostro created this order

```json
[
  "EVENT",
  "RAND",
  {
    "id": "1d28e7384010491bdbc3311380994bec764e80b8afbea74f02f8b947e944fcae",
    "pubkey": "dbe0b1be7aafd3cfba92d7463edbd4e33b2969f61bd554d37ac56f032e13355a",
    "created_at": 1710431991,
    "kind": 38383,
    "tags": [
      [
        "d",
        "d47b3a6d-0cc3-430d-b0df-d73109130f32"
      ],
      [
        "k",
        "buy"
      ],
      [
        "f",
        "ARS"
      ],
      [
        "s",
        "pending"
      ],
      [
        "amt",
        "100000"
      ],
      [
        "fa",
        "1000"
      ],
      [
        "pm",
        "MP lemon belo brubank uala"
      ],
      [
        "premium",
        "0"
      ],
      [
        "y",
        "mostrop2p"
      ],
      [
        "z",
        "order"
      ]
    ],
    "content": "",
    "sig": "f5775f3ac3f193b8fd8d184bc2504228a44281a7eeb4d3888882fa5ead7ec1a83c17be29ff478e752610b971ed49408b10bb40a65648c887cab1df112f29401e"
  }
]

```

Mostro should reject this new order because the lightning invoice have a wrong amount

**Comment by arkanoider** [comment]
Ok my mental debugger failed, need the real one at home...
Will fix!

**Comment by grunch** [comment]
This is the first case in #199 

```bash
mcli neworder -k buy -c ars -f 1000 -m "MP lemon belo brubank uala" -i lnbcrt500u1pjlx8h2pp59j3gqf4t557y7crssk4vf4s5n8emqh3pa82g4vx4n8ujyfdp03nsdqqcqzzsxqyz5vqsp5jzc9aww26844a6c2sp5nyyv9hvzy9zhapwa78vx5lynx7ylt70gs9qyyssqcvwfpf99ttf7y02tzqj2e7nfzn2tptn0s269pjrd9xw7fspchl35nkfzedlyf65jh8ylq8u433puux8846j6cr4qzzckdhfvg0n0tkqpjxjt8m          
┌──────────┬──────────────┬───────────┬─────────────┬────────────────────────────┬───────────┐
│ Buy/Sell ┆  Sats Amount ┆ Fiat Code ┆ Fiat Amount ┆       Payment method       ┆ Premium % │
╞══════════╪══════════════╪═══════════╪═════════════╪════════════════════════════╪═══════════╡
│    buy   ┆ market price ┆    ARS    ┆     1000    ┆ MP lemon belo brubank uala ┆     0     │
└──────────┴──────────────┴───────────┴─────────────┴────────────────────────────┴───────────┘
Check your order! Is it correct? (Y/n) > 
Message correctly sent to Mostro! Check messages with getdm or listorders command
Bye Bye!
```

Mostro broadcasted this event:
```json
[
  "EVENT",
  "RAND",
  {
    "id": "0a2441780629553ab6b0e0ae225f8bc0214810090309da23010736f189b4fe86",
    "pubkey": "dbe0b1be7aafd3cfba92d7463edbd4e33b2969f61bd554d37ac56f032e13355a",
    "created_at": 1710437949,
    "kind": 38383,
    "tags": [
      [
        "d",
        "534141dd-9cd0-4e97-97e0-a478777fe152"
      ],
      [
        "k",
        "buy"
      ],
      [
        "f",
        "ARS"
      ],
      [
        "s",
        "pending"
      ],
      [
        "amt",
        "0"
      ],
      [
        "fa",
        "1000"
      ],
      [
        "pm",
        "MP lemon belo brubank uala"
      ],
      [
        "premium",
        "0"
      ],
      [
        "y",
        "mostrop2p"
      ],
      [
        "z",
        "order"
      ]
    ],
    "content": "",
    "sig": "06b379b784287b60abc4ff76f468b90a57e21b4c141e523501dda61f357d78ddd356b3c2cb7e8503e2c18fe3a3c77a28086aff525aca7e899272780b7dbb41bf"
  }
]

```

**Review by grunch — CHANGES_REQUESTED** [review]
There a important thing to fix, I don't know if the user creates an order like this
 ```
 mcli neworder -k buy -c ars -f 1000 -m "MP lemon belo brubank uala" -i lnbcrt500u1pjlducupp5xf850g8v4v3z43f4x5nd08za8vcfvepd3qmcssx5el0cye8vty2qdqqcqzzsxqyz5vqsp5agudul88m0dgakxtgxjs9ney7fksn6u7cuw2lf453cdql96hj00q9qyyssqd36wwrkfz6fyw4dqp0mhehm4pl2jn6dchcw3s5gca39xs39t9n9xezv4f0hxue7auxzd7s4j8xx7v04xxrqwgwvz0tmmvkxnwd9hc3qq2k5ed9 -a 50000
 ```
 Mostro will create the order without fee for the buyer and the buyer (and seller) should be charged with half of the mostro.fee on settings

**Comment by arkanoider** [comment]
Clear @grunch , this should be fixed on cli side in your opinion (and webclient side) because i thinl otherwise mostro have to send a dm.to buyer with right invoice amount, or am I missing your point?

**Comment by grunch** [comment]
> Clear @grunch , this should be fixed on cli side in your opinion (and webclient side) because i thinl otherwise mostro have to send a dm.to buyer with right invoice amount, or am I missing your point?

In this case Mostro should reject that order, if a buyer wants to send am invoice with amount they should know the right amount, if they don't they can send an amountless invoice, don't send invoice on creation or send a LN address

**Comment by arkanoider** [comment]
So they have to sum manually the fee to the invoice in this case? Rejecting is not a problem, just thinkin if for the user is good...

**Comment by grunch** [comment]
> So they have to sum manually the fee to the invoice in this case? Rejecting is not a problem, just thinkin if for the user is good...

yes they have to calculate it manually, this case is not going to happen frequently, we also can reject all new orders with invoices with amount if you want, probably this too much thinking for something that nobody will use

**Comment by arkanoider** [comment]
Agree let's do it....
Tomorrow will fix

**Comment by arkanoider** [comment]
> > Still speakin loud @grunch , I agree with you that it's an overengineering to add invoice and amount to the `neworder` command.
> > What do you say to remove also from mostro cli the option to create an order with a sats amount and an invoice? User has `premium` options to set his greed level on the order.
> > Maybe also @bilthon could remove the fixed amount option from the interface at this point and also lighting invoice form from buy option.
> > Don't know if I am missing some points here, let me know.
> > Anyway I will add a check on mostro side to reject neworder with an attached invoice with amount != 0
> 
> we should allow buyers to add amountless invoices any time

Clear! 

Now should be like that because I added this block of code in `order.rs`:
```Rust
// Reject all new invoices in a neworder with amount != 0
        if let Some(invoice) = msg.get_inner_message_kind().get_payment_request() {
            let invoice = decode_invoice(&invoice)?;
            if let Some(invoice_sats) = invoice.amount_milli_satoshis().map(|sats| sats / 1000) {
                if invoice_sats !=0 {
                    let message = Message::cant_do(
                        order.id,
                        None,
                        Some(Content::TextMessage(
                            String::from("Invoice with an amount different from zero receive on new order, please send 0 amount invoice or no invoice at all!"                  
                        ))),
                    );
                    let message = message.as_json()?;
                    send_dm(client, my_keys, &event.pubkey, message).await?;
                    return Ok(());
                }
            }
        }
```
When a new order arrive ( sell or buy ) if invoice is present with amount != 0, Mostro will reject it and send a dm to user.

In all the other case invoice should be accepted, because i did not change `is_valid_invoice ` function.

This is not tested at all because I am in office, if you can give a try if this could be a desired behaviour.

In the end I just changed `order.rs` using a different filter on invoice sats value, while `takesell` and `takebuy` checks are still the same.

**Review by grunch — APPROVED** [review]
congrats buddy, great job!

**Pull request merged**
