### PR TITLE
additions to have tokens for dispute

### PR DESCRIPTION
**Pull request by arkanoider**
Hi @grunch ,

addition of tokens for disputes. Look [here](https://github.com/MostroP2P/mostro-core/pull/61).

### CODE REVIEW

**Review by Catrya — COMMENTED** [review]
Hi @arkanoider  when an admin takes the dispute, Mostro is not sending the users' tokens to the admin.
It sends the token to the seller and the buyer correctly, but not to the admin.

**Comment by Catrya** [comment]
> Hola@arkanoider Cuando un administrador acepta la disputa, Mostro no envía los tokens de los usuarios al administrador. Envía los tokens al vendedor y al comprador correctamente, pero no al administrador.

Look. To the buyer:
`{"order":{"version":1,"id":"73a59f62-832d-418f-8a29-06249b3a497f","pubkey":null,"action":"admin-took-dispute","content":{"peer":[{"pubkey":"000000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx05"},54793]}}}`

To the seller:
`{"order":{"version":1,"id":"73a59f62-832d-418f-8a29-06249b3a497f","pubkey":null,"action":"admin-took-dispute","content":{"peer":[{"pubkey":"000000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx05"},22013]}}}`

To the admin:
```
Action: AdminTookDispute
Content: Some(
    Order(
        SmallOrder {
            id: Some(
                73a59f62-832d-418f-8a29-06249b3a497f,
            ),
            kind: Some(
                Sell,
            ),
            status: Some(
                Dispute,
            ),
            amount: 500,
            fiat_code: "CUP",
            min_amount: None,
            max_amount: None,
            fiat_amount: 5,
            payment_method: "token",
            premium: 0,
            master_buyer_pubkey: Some(
                "000xxxxxxxxxxxxxxxxxxxxxxxxxxx4e",
            ),
            master_seller_pubkey: Some(
                "000xxxxxxxxxxxxxxxxxxxxxxxxxxxx4",
            ),
            buyer_invoice: Some(
                "lnbcrt5u1pndpyaepp5wmjw8d2qfqkqcwdrxztzl9d4fu8zj77c2x7c4qfhfcjfrd7rfygqdqqcqzzsxqyz5vqsp5smm8q9v8mv4espz49z9lk0vkjfyzvvxskgftexc9w47vgmnwx68q9qyyssq3a0cam2kdkjj9el8epdtt5628t7dh9h2cvc906xuwvkwfc02dgmxr8p0hrplllf5nwul5mml25heqctd7n8jh6ra9snzzhjsl0kktqgq0kc5s0",
            ),
            created_at: Some(
                1724945187,
            ),
            expires_at: Some(
                1725031587,
            ),
        },
    ),
)
```

**Review by Catrya — COMMENTED** [review]
It works fine, although it still doesn't show the admin the tokens of the deputies, but in the logs it does show that Mostro sends them, so it must be from Mostro cli as you told me @arkanoider

**Comment by grunch** [comment]
Great job @arkanoider there is only one thing to be done, both tokens need to have the same length, let's use 3 digit tokens

**Review by grunch — CHANGES_REQUESTED** [review]
Great job @arkanoider there is only one thing to be done, both tokens need to have the same length, let's use 3 digit tokens

**Comment by arkanoider** [comment]
> Great job @arkanoider there is only one thing to be done, both tokens need to have the same length, let's use 3 digit tokens

You mean between 100 - 999 right?

**Comment by arkanoider** [comment]
> Great job @arkanoider there is only one thing to be done, both tokens need to have the same length, let's use 3 digit tokens

Added token fixed with 3 digit from `100 to 999`

**Review by grunch — APPROVED** [review]
tACK, great job buddy!

**Pull request merged**
