### PR TITLE
hotfix #303

### PR DESCRIPTION
**Pull request by arkanoider**
@grunch @Catrya 

hotfix to avoid panic #303.

### CODE REVIEW

**Review by Catrya — APPROVED** [review]
There is no panic error anymore!

**Comment by Catrya** [comment]
Although when admin does admsettle, the message Mostro sent is ¨Dispute not taken by you¨
But it should be something like ¨This order has already been cancelled by its users"
Maybe we could consider putting this in a new issue?

**Comment by arkanoider** [comment]
> Although when admin does admsettle, the message Mostro sent is ¨Dispute not taken by you¨ But it should be something like ¨This order has already been cancelled by its users" Maybe we could consider putting this in a new issue?

I will continue on this issue @Catrya , will look to have a more consistent error for user in these case.

**Comment by grunch** [comment]
> Although when admin does admsettle, the message Mostro sent is ¨Dispute not taken by you¨ But it should be something like ¨This order has already been cancelled by its users" Maybe we could consider putting this in a new issue?

Probably we should start doing the new stuff following what is asked in #312, so we don't have to send any text string to the user, we should send a message with an action that let know to the client what happened, you can see the list of actions [here](https://docs.rs/mostro-core/latest/mostro_core/message/enum.Action.html) so we can use `CooperativeCancelAccepted` but if you think we should use a different one we can discuss it here

**Review by Catrya — COMMENTED** [review]
There is no panic error anymore, and returns the message "cooperative-cancel-accepted"

But now if there is a cooperative cancellation and the admin tries to cancel anyway, the message it returns is "Can't settle an order with status different than dispute!". But before it allowed it even though it had no effect

**Review by Catrya — COMMENTED** [review]
There is no panic error anymore, and returns the message "cooperative-cancel-accepted"

But now if there is a cooperative cancellation and the admin tries to cancel anyway, the message it returns is "Can't settle an order with status different than dispute!". But before it allowed it even though it had no effect

**Comment by arkanoider** [comment]
I will

**Comment by arkanoider** [comment]
> But now if there is a cooperative cancellation and the admin tries to cancel anyway, the message it returns is "Can't settle an order with status different than dispute!". But before it allowed it even though it had no effect

I think that's just because I added the check only in `admin_settle` file and not in `admin_cancel`. Doing it in my new branch on Mostro.

**Pull request closed without merging**
